apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: fs_drift-hostpath-benchmark
  namespace: benchmark-operator
spec:
  test_user: homer_simpson
  # to separate this test run from everyone else's
  clustername: test_ci
  system_metrics:
    collection: true
    prom_url: https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091
    es_url: ${ES_SERVER}
    prom_token: ${PROMETHEUS_TOKEN}
    metrics_profile: node-metrics.yml
  # where elastic search is running
  elasticsearch:
    url: ${ES_SERVER}
    index_name: ripsaw-fs_drift
  metadata:
    collection: true
  hostpath: /mnt/vda1/fs_drift
  workload:
    name: fs_drift
    args:
      worker_pods: 1
      threads: 5
      max_file_size_kb: 4
      max_files: 1000
      duration: 10
      debug: true
